org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=recolor
mod.name=Recolor
mod.group=bluebird
mod.version=1.1
mod.version_prefix=
mod.version_suffix=
mod.authors=BluebirdDevs
mod.contributors=
mod.license=ARR
mod.description=Allows changing hardcoded colors in the game with a resource pack
mod.sources_url=https://github.com/BluebirdDevs/recolor
mod.homepage_url=https://github.com/BluebirdDevs/recolor
mod.issues_url=https://github.com/BluebirdDevs/recolor/issues

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

# Publishing
publish.dryrun=false

publish.modrinth.id=Ky4LN4zD
publish.curseforge.id=1520443

publish.modrinth=false
publish.curseforge=false

publish.release.fabric=stable
publish.release.neoforge=stable
publish.release.forge=stable
